---
label: Recipe
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
  description: The recipe title
- name: method
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Method
  description: The cooking directions
- name: cuisine
  type: tag_list
  default: []
  label: Cuisine
